# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
# modelarts
enable_modelarts: False
data_url: ""
train_url: ""
save_dir: ""
train_path: ""
test_path: ""
local_data_url: "/cache/dataset"
local_train_url: "/cache/train_out"
local_train_path: "/cache/dataset/train.mindrecord0"
local_test_path: "/cache/dataset/test.mindrecord0"
checkpoint_path: ""
local_checkpoint_path: "/cache/save/best.ckpt"
device_target: "Ascend"
device_id: 0
enable_profiling: False
# train-related
run_distribute: False
save_check: True
feature_dim: 39
batch_size: 64
hidden_size: 128
test_batch_size: 1
n_class: 62
n_layer: 2
max_sequence_length: 1555
max_label_length: 75
lr_init: 0.005
clip_value: 5.0
epoch: 300
save_checkpoint_steps: 18
keep_checkpoint_max: 100
interval: 5
dataset_sink_mode: True
beam: False
train_eval: True
#preprocess data related
dataset_dir: "./dataset"
train_dir: ""
test_dir: ""
train_name: "train.mindrecord"
test_name: "test.mindrecord"
#export-related
file_name: "ctc"
file_format: "MINDIR"
#preprocess-related
result_path: "./preprocess_Result"
#postprocess-related
label_dir: ""
seqlen_dir: ""
result_dir: "./result_Files"
---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
save_dir: "Directory to save model"
train_path: "Path of train dataset"
test_path: "Path of test dataset"
local_data_url: "Local url for modelarts"
local_train_url: "Local url for modelarts"
local_train__path: "Local url for train_dataset"
local_test_path: "local url for test_dataset"
checkpoint_path: "Path of checkpoint"
local_checkpoint_path: "Local path of checkpoint"
device_target: "Ascend"
device_id: "Device id"
enable_profiling: "Use profiling"
run_distribute: "Train distribute"
feature_dim: "Feature dim"
batch_size: "Batch size"
hidden_size: "Hidden size"
n_class: "Num of class"
n_layer: "Layers"
lr_init: "Learning rate"
clip_value: "global clip value"
epoch: "Epoch of train"
save_checkpoint_steps: "Steps to save model"
keep_checkpoint_max: "Max number of checkpoints"
interval: "Interval of eval"
max_sequence_length: "Length of padded sequence"
max_label_length: "Length of padded label"
dataset_sink_mode: "Whether to use dataset sinkmode，default:True"
svae_check: "Whether to save_checkpoint"
beam: "Whether to use prefix_beam_search,only for eavl,default:False"
train_eval: "Whether to eval when train"
file_name: "filename of export file"
file_format: "format of export file"
result_path: "preprocess result path"


